development:
  adapter: postgresql
  encoding: unicode
  database: voicey_development
  pool: 5
  username: skyxu
  password: "12345678"

test:
  adapter: postgresql
  encoding: unicode
  database: voicey_test
  pool: 5
  username: skyxu
  password: "12345678"


production:
  adapter: postgresql
  encoding: unicode
  database: voicey_production
  pool: 5
  username: skyxu
  password: "12345678"
