# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 439d85110fadace01fe3022e8817ce7bf815e861ed899a5e9a19fedfce3d1604f3399419bb84679a1befd61577a43de24d62671d0a7dc3875582db6920e2c061

test:
  secret_key_base: 8651a347af2fdcd018019bcbea9310cf3d07c97ba32e678157e9e71eddb532e278aeeb3665c25329648605b3a437f7da042c5a86b1508f3311c780ce66cf53e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
